name: mpesa_analyzer_flutter
description: Phase 1 Flutter shell for M-PESA Analyzer.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

